[all]
exclude-files = [
    "crates/cli/src/logic/init_logging.rs",
    "crates/cli/src/logic/run.rs",
    "crates/cli/src/logic/get_input.rs",
    "crates/cli/src/main.rs",
]
verbose = false
timeout = "2m"
locked = true
all-features = true
jobs = 1
out = ["Html"]
